version: '3.8' 

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper_service
    ports:
      - "2181:2181"  
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka_service
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181 # use 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
